---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 80
      nodePort: 32700
  selector:
    app: nginx
  type: LoadBalancer
